name: TGW

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::434097521299:role/terraform-demo
          aws-region: ap-south-1

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform
        run: |
          terraform plan 
            -var="hub_role="arn:aws:iam::434097521299:oidc-provider/token.actions.githubusercontent.com"
            -var="spoke_role="arn:aws:iam::434097521299:oidc-provider/token.actions.githubusercontent.com"

      - name: Terraform Apply
        working-directory: terraform
        run: |
          terraform apply -auto-approve 
            -var="hub_role="arn:aws:iam::434097521299:oidc-provider/token.actions.githubusercontent.com" 
            -var="spoke_role="arn:aws:iam::434097521299:oidc-provider/token.actions.githubusercontent.com"